# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20191104_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='', upload_to='articles/'),
        ),
    ]
