# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20191105_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='image.jpg', upload_to='articles/'),
        ),
    ]
